import pytest
import time
import selenium.webdriver as webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from base_pages.Home_page import Home_page_menu
from base_pages.Home_page import form_filling
from utilities.config_reader import ReadConfig_menu, ReadConfig_contact_form
from utilities.custom_log import Log_gen

class Test:
    url = ReadConfig_menu.get_application_url()
    demo_booking = ReadConfig_menu.get_booking_button()
    contact_sales = ReadConfig_menu.get_contact_sales_button()
    cross_button = ReadConfig_menu.get_cross_button()
    name = ReadConfig_contact_form.get_name()
    phone_number = ReadConfig_contact_form.get_phone_number()
    email = ReadConfig_contact_form.get_email()
    country = ReadConfig_contact_form.get_country()
    no_of_employe = ReadConfig_contact_form.get_number_of_employes()
    company = ReadConfig_contact_form.get_company_name()
    #recaptcha = ReadConfig_contact_form.get_recaptcha()
    submite_button = ReadConfig_contact_form.get_contact_sales()
    job_title = ReadConfig_contact_form.get_job_title()
    your_message = ReadConfig_contact_form.get_your_message() 
    log = Log_gen.create_log()

    def test_01_title_verification(self):
        self.log.info("-----------------Test-01------------------")
        self.driver = webdriver.Chrome()
        browser = Home_page_menu(self.driver)
        #self.log.info("[+] Opening the Home page")
        browser.open_home_page(self.url)
        if self.driver.title == "Human Resources Management Software | OrangeHRM 1":
            self.log.info("[+] Test case 01 Passed")
            self.driver.quit()
            assert True
        else:
            self.log.info("[+] Test case 01 Failed")
            self.driver.save_screenshot(r"C:\Users\pranj\OneDrive\Desktop\Orangehrm\screenshots\test_01.png")
            self.driver.quit()
            assert False
    
    def test_02_positive_verfication_of_sales_contact_form(self):
        self.log.info("-----------------Test-02------------------")
        self.driver = webdriver.Chrome()
        browser = Home_page_menu(self.driver)
        #self.log.info("[+] Testing positivie test case on sale contact form")
        #self.log.info("[+] Opening Homepage")
        browser.open_home_page(self.url)
        #browser.Accept_cookie(self.cross_button)
        #self.log.info("[+] Clicking on 'sales contact' button")
        browser.click_contact_sales_button(self.contact_sales)
        #self.log.info("[+] Starting the form filling")
        form = form_filling(self.driver)
        #self.log.info("[+] Entering the name")
        form.enter_name(self.name)
        #self.log.info("[+] Entering the phone number")
        form.enter_phone_number(self.phone_number)
        #self.log.info("[+] Entering the email")
        form.enter_email(self.email)
        #form.enter_company(self.company)
        #self.log.info("[+] Entering the country")
        form.enter_country(self.country)
        #self.log.info("[+] Entering the total number of employe")
        form.enter_no_of_employe(self.no_of_employe)
        #self.log.info("[+] Entering the job title")
        form.job_title(self.job_title)
        #self.log.info("[+] Entering your message")
        form.your_message(self.your_message)
        #self.log.info("[+] Verifying the recaptcha")
        time.sleep(30)
        #self.log.info("[+] Submiting the form")
        form.submit(self.submite_button)
        form.test_verification_sales_contact()

    
    def test_03_positive_verificatio_of_demo_contact_form(self):
        self.log.info("-----------------Test-03------------------")
        self.driver = webdriver.Chrome()
        browser = Home_page_menu(self.driver)
        #self.log.info("[+] Opening the Homepage")
        browser.open_home_page(self.url)
        #self.log.info("[+] Clicking the demo booking button")
        browser.click_booking_button(self.demo_booking)
        #self.log.info("[+] Starting the form filling")
        form = form_filling(self.driver)
        #self.log.info("[+] Entering name")
        form.enter_name(self.name)
        #self.log.info("[+] Entering phone number")
        form.enter_phone_number(self.phone_number)
        #self.log.info("[+] Entering email")
        form.enter_email(self.email)
        #self.log.info("[+] Entering company")
        form.enter_company(self.company)
        #self.log.info("[+] Entering country")
        form.enter_country(self.country)
        #self.log.info("[+] Entering number of employe")
        form.enter_no_of_employe(self.no_of_employe)
        #self.log.info("[+] Veryfing the captcha")
        time.sleep(30)
        #self.log.info("[+] Submitting the form")
        form.submit(self.submite_button)
        form.test_verification_demo_contact()

    def test_04_negative_verfication_of_sales_contact_form(self):
        self.log.info("-----------------Test-04------------------")
        self.driver = webdriver.Chrome()
        browser = Home_page_menu(self.driver)
        #self.log.info("[+] Opening the Homepage")
        browser.open_home_page(self.url)
        #browser.Accept_cookie(self.cross_button)
        #self.log.info("[+] Opening the Homepage")
        browser.click_contact_sales_button(self.contact_sales)
        form = form_filling(self.driver)
        #form.enter_name(self.name)
        form.enter_phone_number(self.phone_number)
        form.enter_email(self.email)
        #form.enter_company(self.company)
        form.enter_country(self.country)
        form.enter_no_of_employe(self.no_of_employe)
        form.job_title(self.job_title)
        form.your_message(self.your_message)
        time.sleep(30)
        form.submit(self.submite_button)
        form.test_negative_verification_sales_contact()

    def test_05_negative_verificatio_of_demo_contact_form(self):
        self.log.info("-----------------Test-05------------------")
        self.driver = webdriver.Chrome()
        browser = Home_page_menu(self.driver)
        browser.open_home_page(self.url)
        browser.click_booking_button(self.demo_booking)
        form = form_filling(self.driver)
        form.enter_name(self.name)
        form.enter_phone_number(self.phone_number)
        form.enter_email(self.email)
        form.enter_company(self.company)
        #form.enter_country(self.country)
        form.enter_no_of_employe(self.no_of_employe)
        time.sleep(30)
        form.submit(self.submite_button)
        form.test_negative_verification_demo_contact()
        